first commit
0le8/go-first-floor-sprint-five pull request #1
Opened 2024-02-25 18:48 UTC by 0le8

2024-02-25 20:51 UTC, robotomize requested changes
Привет, отлично поработали, но есть несколько моментов, которые нужно исправить

2024-02-25 20:51 UTC, robotomize commented on main.go
> +	return (CaloriesWeightMultiplier * w.Weight + (math.Pow(w.meanSpeed(), 2) / w.Height) * CaloriesSpeedHeightMultiplier *  float64(w.Weight) ) * w.Duration.Hours() * MinInHours
Привет тут есть несколько моментов

- Нужно перевести рост из сантиметров в метры, воспользуйтесь для этого уже созданной константой
- Нужно первести скорость в м/c для этого воспользуйтесь соответствующей константой

2024-02-26 07:54 UTC, 0le8 commented on main.go
> +	return (CaloriesWeightMultiplier * w.Weight + (math.Pow(w.meanSpeed(), 2) / w.Height) * CaloriesSpeedHeightMultiplier *  float64(w.Weight) ) * w.Duration.Hours() * MinInHours
Исправил в коммите https://github.com/0le8/go-first-floor-sprint-five/pull/1/commits/707e6110236919dfd6ed1a3dd8c5429cd9a8c7af

2024-02-26 13:18 UTC, robotomize approved these changes
В формуле все же ошибка отписал в комментах, но поправьте это уже обязательно самостоятельно, двигаемся дальше, принято

2024-02-26 13:18 UTC, robotomize commented on main.go
> +	heightInM := w.Height * CmInM
Нужно перевести из сантиметров в метры, в этой формуле нужно разделить(в предыдущем задании эта же формула была)

2024-02-26 16:12 UTC, 0le8 commented on main.go
> +	heightInM := w.Height * CmInM
Действительно туплю =) Поправил в [fix formula in Walking Calories](https://github.com/0le8/go-first-floor-sprint-five/pull/1/commits/958e2678400ee07065dc42c64f7ff59fd7a69bf7)

2024-02-27 18:17 UTC, merged